# Generated by Django 6.0.3 on 2026-03-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cama'),
    ]

    operations = [
        migrations.AddField(
            model_name='cama',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cama_asignada', to='api.paciente'),
        ),
    ]
