# Generated by Django 6.0.3 on 2026-04-07 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cama_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrisanchoRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('edad_anios', models.PositiveSmallIntegerField()),
                ('pb_menos_sd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pb_dato', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pb_mas_sd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pct_menos_sd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pct_dato', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pct_mas_sd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cmb_menos_sd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cmb_dato', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cmb_mas_sd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amb_menos_sd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amb_dato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amb_mas_sd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agb_menos_sd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agb_dato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agb_mas_sd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referencia Frisancho',
                'verbose_name_plural': 'Referencias Frisancho',
                'db_table': 'frisancho_ref',
                'unique_together': {('genero', 'edad_anios')},
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('edad_meses', models.PositiveSmallIntegerField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('talla_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pb_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pct_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='api.paciente')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
                'db_table': 'medidas',
            },
        ),
        migrations.CreateModel(
            name='OmsRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('edad_meses', models.PositiveSmallIntegerField()),
                ('imc_menos_sd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc_mediana', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc_mas_sd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla_menos_sd_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla_mediana_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla_mas_sd_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referencia OMS',
                'verbose_name_plural': 'Referencias OMS',
                'db_table': 'oms_ref',
                'unique_together': {('genero', 'edad_meses')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_ideal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dif_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cmb_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amb_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agb_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('z_imc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dx_z_imc', models.CharField(blank=True, max_length=100, null=True)),
                ('z_talla', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dx_z_talla', models.CharField(blank=True, max_length=100, null=True)),
                ('z_pb', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dx_z_pb', models.CharField(blank=True, max_length=100, null=True)),
                ('z_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dx_z_pct', models.CharField(blank=True, max_length=100, null=True)),
                ('z_cmb', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dx_z_cmb', models.CharField(blank=True, max_length=100, null=True)),
                ('z_amb', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dx_z_amb', models.CharField(blank=True, max_length=100, null=True)),
                ('z_agb', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dx_z_agb', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
                ('frisancho_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.frisanchoref')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='api.medida')),
                ('oms_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.omsref')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
                'indexes': [models.Index(fields=['medida_id'], name='evaluacione_medida__ceb126_idx'), models.Index(fields=['oms_ref_id'], name='evaluacione_oms_ref_6aa709_idx'), models.Index(fields=['frisancho_ref_id'], name='evaluacione_frisanc_4159d7_idx')],
            },
        ),
    ]
