# Generated by Django 6.0.3 on 2026-04-21 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_frisanchoref_medida_omsref_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg_at', models.DecimalField(decimal_places=2, max_digits=6)),
                ('talla_cm_at', models.DecimalField(decimal_places=2, max_digits=5)),
                ('geb_kcal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('factor_actividad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('factor_lesion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('get_kcal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kcal_por_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('calculado_en', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_nutricionales', to='api.medida')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos_nutricionales', to='api.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_nutricionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimiento Nutricional',
                'verbose_name_plural': 'Requerimientos Nutricionales',
                'db_table': 'requerimientos_nutricionales',
            },
        ),
        migrations.CreateModel(
            name='MoleculaCalorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('talla_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kilocalorias_totales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proteinas_g_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_grasas', models.DecimalField(decimal_places=4, max_digits=5)),
                ('grasas_g_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbohidratos_g_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kilocalorias_proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('kilocalorias_grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('kilocalorias_carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_proteinas', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('porcentaje_carbohidratos', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moleculas_caloricas', to='api.medida')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moleculas_caloricas', to='api.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moleculas_caloricas', to=settings.AUTH_USER_MODEL)),
                ('requerimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moleculas_caloricas', to='api.requerimientonutricional')),
            ],
            options={
                'verbose_name': 'Molécula Calórica',
                'verbose_name_plural': 'Moléculas Calóricas',
                'db_table': 'molecula_calorica',
            },
        ),
        migrations.AddIndex(
            model_name='requerimientonutricional',
            index=models.Index(fields=['paciente'], name='requerimien_pacient_1c8122_idx'),
        ),
        migrations.AddIndex(
            model_name='requerimientonutricional',
            index=models.Index(fields=['estado'], name='requerimien_estado_b58a01_idx'),
        ),
        migrations.AddIndex(
            model_name='moleculacalorica',
            index=models.Index(fields=['paciente'], name='molecula_ca_pacient_2212ad_idx'),
        ),
        migrations.AddIndex(
            model_name='moleculacalorica',
            index=models.Index(fields=['requerimiento'], name='molecula_ca_requeri_407728_idx'),
        ),
        migrations.AddIndex(
            model_name='moleculacalorica',
            index=models.Index(fields=['estado'], name='molecula_ca_estado_26e759_idx'),
        ),
    ]
